function startup
%%Run me to add all subdirectories into the MATLAB path
    folder = fileparts(which(mfilename));
    addpath(genpath(folder));
    
    % Be aware: The below code will modify your MATLAB plot settings (at
    % least until you close and re-open it again)
    ColorBarFontSize = 20;
    set(groot, 'defaultAxesTickLabelInterpreter', 'latex', ...
               'defaultLegendInterpreter','latex', ...
               'defaultTextInterpreter', 'latex', ...
               'defaultColorBarTickLabelInterpreter','Latex', ...
               'defaultAxesFontSize', 20, ...
               'defaultAxesLabelFontSizeMultiplier', 1.25, ...
               'defaultAxesTitleFontSizeMultiplier', 1.25, ...
               'defaultLineLineWidth', 1, ...
               'defaultLineMarkerSize', 8, ...
               'defaultAxesLineWidth', 1.5, ...
               'defaultColorBarLineWidth', 1.5, ...
               'defaultColorBarFontSize', ColorBarFontSize, ...
               'defaultLegendFontSize', 0.85*20*1.25);
end


